---
# Source: dra-example-driver/templates/deviceclass.yaml
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: gpu.example.com
spec:
  selectors:
  - cel: 
      expression: "device.driver == 'gpu.example.com'"
  {{- if .ExtendedResourceName}}
  extendedResourceName: "{{.ExtendedResourceName}}"
  {{- end}}
