---
# Source: dra-example-driver/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dra-example-driver-service-account
  namespace: {{.Namespace}}
  labels:
    helm.sh/chart: dra-example-driver-0.0.0-dev
    app.kubernetes.io/name: dra-example-driver
    app.kubernetes.io/instance: dra-example-driver
    app.kubernetes.io/version: "v0.2.0"
    app.kubernetes.io/managed-by: Helm