apiVersion: batch/v1
kind: Job
metadata:
  name: {{.Name}}
  labels:
    group: test-job
    job-type: long-running
spec:
  parallelism: {{.Replicas}}
  completions: {{.Replicas}}
  completionMode: {{.Mode}}
  activeDeadlineSeconds: 86400 # 24 hours
  template:
    metadata:
      labels:
        group: test-pod
        job-type: long-running
    spec:
      restartPolicy: Never
      containers:
        - name: {{.Name}}
          image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
          args:
            - {{.Sleep}}
          resources:
          {{ if .ExtendedResource }}
            limits:
              example.com/gpu: "1"
          {{ else }}
            claims:
            - name: gpu
      resourceClaims:
      - name: gpu
        resourceClaimTemplateName: single-gpu-0
          {{ end }}
